 // swift-tools-version: 6.1
name: Swift Build

on:
  push:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Swift Package
        run: swift build
